#!/bin/bash
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

cd $SCRIPTDIR/modules/terraform-aws-vault-client
export TF_VAR_vault_client_ami_id=none
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan

cd $SCRIPTDIR/modules/terraform-aws-render-vpc-vault-vpc-peering
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan

cd $SCRIPTDIR/modules/terraform-aws-render-vpc-cloud9-peering
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan

cd $SCRIPTDIR/modules/terraform-aws-render-vpc
terraform plan -out=tfplan -input=false -destroy
terraform apply -input=false tfplan