#!/bin/bash
set -e

exit_if_error() {
  local exit_code=$1
  shift
  [[ $exit_code ]] &&               # do nothing if no error code passed
    ((exit_code != 0)) && {         # do nothing if error code is 0
      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
      exit "$exit_code"             # we could also check to make sure
                                    # error code is numeric when passed
    }
}

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

source $SCRIPTDIR/update_vars.sh

# Raise error if var isn't defined.
if [[ -z "$AWS_DEFAULT_REGION" ]]; then
    exit_if_error 1 "AWS_DEFAULT_REGION not defined."
fi
if [[ -z "$TF_VAR_bucket_extension" ]]; then
    exit_if_error 1 "TF_VAR_bucket_extension not defined."
fi

cd $SCRIPTDIR/modules/terraform-aws-render-vpc
./generate-plan
terraform apply -input=false tfplan # Ensure Main VPC exists

cd $SCRIPTDIR/modules/terraform-aws-render-vpc-cloud9-peering
./generate-plan
terraform apply -input=false tfplan # Ensure VPC is peered with this cloud9 VPC

cd $SCRIPTDIR/modules/terraform-aws-render-vpc-vault-vpc-peering
./generate-plan
terraform apply -input=false tfplan # Ensure Render VPC is peered with Vault VPC

cd $SCRIPTDIR/modules/terraform-aws-vault-client
./generate-plan
terraform apply -input=false tfplan # Ensure Vault / Consul instances are running, and configure VPC peering with the current cloud 9 VPC.