- name: init ubl licence info if first time install
  shell: | 
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ ubl_url }}"}})'
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ ubl_activation_code }}"}})'
  when: ubl
  # no_log: true
  become: true
  register: deadline_ubl

- debug:
    msg: "{{ deadline_ubl.stdout }}"
  when: ubl

- name: update ubl licence info if already installed
  shell: |
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ ubl_url }}"}})'
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ ubl_activation_code }}"}})'
  when: ubl
  # no_log: true
  become: true
  register: deadline_ubl

- debug:
    msg: "{{ deadline_ubl.stdout }}"
  when: ubl