- name: init ubl licence info if first time install, and enable other config default to ease usage.
  shell: | 
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ ubl_url }}"}})'
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ ubl_activation_code }}"}})'
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{SlaveUseIPAddress: true}})' # Required over VPN without DNS
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{PulseUseIPAddress: true}})' # Required over VPN without DNS
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{EnableRemoteAdministration: true}})' # Required over VPN to configure deadline
    ./{{ mongo_executable }} --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{EnableRemoteCommandWhitelist: false}})'
  when: ubl_url
  # no_log: true
  become: true
  register: deadline_ubl
  with_items:
  - update

- name: show output
  debug:
    msg: "{{ deadline_ubl.stdout }}"
  when: ubl_url


# - debug:
#     msg: "{{ deadline_ubl.stdout }}"
#   when: ubl_url

# - name: update ubl licence info if already installed
#   shell: |
#     cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
#     ./{{ mongo_executable }} --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ ubl_url }}"}})'
#     ./{{ mongo_executable }} --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ ubl_activation_code }}"}})'
#   when: ubl_url
#   # no_log: true
#   become: true
#   register: deadline_ubl

