#!/bin/bash
set -e

exit_if_error() {
  local exit_code=$1
  shift
  [[ $exit_code ]] &&               # do nothing if no error code passed
    ((exit_code != 0)) && {         # do nothing if error code is 0
      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
      exit "$exit_code"             # we could also check to make sure
                                    # error code is numeric when passed
    }
}

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
namespace="$TF_VAR_vpcname-$(basename $SCRIPTDIR)"
echo "Namespace for terraform remote state: $namespace"

# Raise error if var isn't defined.
if [[ -z "$TF_VAR_resourcetier" ]]; then
    exit_if_error 1 "TF_VAR_resourcetier not defined."
fi
if [[ -z "$AWS_DEFAULT_REGION" ]]; then
    exit_if_error 1 "AWS_DEFAULT_REGION not defined."
fi
if [[ -z "$TF_VAR_bucket_extension" ]]; then
    exit_if_error 1 "TF_VAR_bucket_extension not defined."
fi
# init the s3 backend if it doesn't exist.

# manifest="$SCRIPTDIR/modules/vault-client-ami/manifest.json"
# if [[ -f "$manifest" ]]; then
#     export TF_VAR_centos7_ami="$(jq -r '.builds[] | select(.name == "centos7-ami") | .artifact_id' "$manifest" | tail -1 | cut -d ":" -f2)"
#     echo "Found centos7_ami in manifest: TF_VAR_centos7_ami=$TF_VAR_centos7_ami"
#     export TF_VAR_vault_client_ami_id=$TF_VAR_centos7_ami
#     echo "TF_VAR_vault_client_ami_id=$TF_VAR_vault_client_ami_id"
# else
#     echo "Manifest for ami does not exist.  Build the base ami and try again."
#     exit 1
# fi

export TF_VAR_centos7_ami="ami-018ba26c187b7edb3"
export TF_VAR_vault_client_ami_id=$TF_VAR_centos7_ami
echo "TF_VAR_vault_client_ami_id=$TF_VAR_vault_client_ami_id"

terraform init \
    -input=false \
    -backend-config="bucket=state.terraform.$TF_VAR_bucket_extension" \
    -backend-config="key=$TF_VAR_resourcetier/$namespace/terraform.tfstate" \
    -backend-config="region=$AWS_DEFAULT_REGION" \
    -backend-config="dynamodb_table=locks.state.terraform.$TF_VAR_bucket_extension"
terraform plan -out=tfplan -input=false 